name: Gitleaks Secret Scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        # This property ensures that even if Gitleaks finds a secret (exit code 1),
        # the job will be marked as 'passed' with a warning, and the Master 
        # Pipeline will proceed to the next job (Trivy).
        continue-on-error: true 
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
