name: "Master Security Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# These permissions are REQUIRED here to be inherited by the sub-workflows
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  call-gitleaks:
    uses: ./.github/workflows/gitleaks.yml
    secrets: inherit

  call-trivy:
    needs: call-gitleaks
    uses: ./.github/workflows/trivy.yml
    secrets: inherit

  call-codeql:
    needs: call-trivy
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
